FROM gradle:jdk8 as build-stage

RUN mkdir -p /home/gradle/app
WORKDIR /home/gradle/app

COPY . .

RUN gradle build

CMD ["java", "-jar", "build/libs/gs-rest-service-0.1.0.jar", "--server.port", "8080"]